'use strict';

exports.__esModule = true;

var _reduxsauce = require('reduxsauce');

exports['default'] = (0, _reduxsauce.createTypes)('\n  ASSETS_RESET\n\n  ASSETS_FETCH\n  ASSETS_SUCCESS\n  ASSETS_FAILURE\n\n  VIRTUAL_ASSETS_FETCH\n  VIRTUAL_ASSETS_SUCCESS\n  VIRTUAL_ASSETS_FAILURE\n\n  ASSET_ROOMS_FETCH\n  ASSET_ROOMS_SUCCESS\n  ASSET_ROOMS_FAILURE\n\n  CUSTOM_ACTIONS_FETCH\n  CUSTOM_ACTIONS_SUCCESS\n  CUSTOM_ACTIONS_FAILURE\n\n  ROOM_AREAS_FETCH\n  ROOM_AREAS_SUCCESS\n  ROOM_AREAS_FAILURE\n\n  INVENTORY_WITHDRAWAL_FETCH\n  INVENTORY_WITHDRAWAL_SUCCESS\n  INVENTORY_WITHDRAWAL_FAILURE\n');