'use strict';

exports.__esModule = true;

var _reduxsauce = require('reduxsauce');

exports['default'] = (0, _reduxsauce.createTypes)('\n  ROOMS_FETCHED\n  FLOORS_FETCHED\n  ROOM_STATUSES_FETCHED\n  ROOM_HOUSEKEEPINGS_FETCHED\n  CALENDAR_FETCHED\n  PLANNINGS_FETCHED\n  ROOM_NOTES_FETCHED\n  CATALOGS_FETCHED\n  TASKS_FETCHED\n  ASSETS_FETCHED\n  VIRTUAL_ASSETS_FETCHED\n  ROOM_AREAS_FETCHED\n  CUSTOM_ACTIONS_FETCHED\n  ASSET_ROOMS_FETCHED\n  INVENTORY_WITHDRAWAL_FETCHED\n  USERS_FETCHED\n  GROUPS_FETCHED\n  GLITCHES_FETCHED\n');