import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET

  ROOMS_FETCHED
  FLOORS_FETCHED
  ROOM_STATUSES_FETCHED
  ROOM_HOUSEKEEPINGS_FETCHED
  ROOM_CATEGORY_FETCHED
  CALENDAR_FETCHED
  PLANNINGS_FETCHED
  ROOM_NOTES_FETCHED
  CATALOGS_FETCHED
  TASKS_FETCHED
  ASSETS_FETCHED
  VIRTUAL_ASSETS_FETCHED
  ROOM_AREAS_FETCHED
  CUSTOM_ACTIONS_FETCHED
  ASSET_ROOMS_FETCHED
  INVENTORY_WITHDRAWAL_FETCHED
  USERS_FETCHED
  GROUPS_FETCHED
  GLITCHES_FETCHED
  HISTORY_FETCHED

  ROOMS_BACKEND
  CALENDAR_BACKEND
  PLANNINGS_BACKEND
  TASKS_BACKEND
  HISTORY_BACKEND
  INVENTORY_WITHDRAWAL_BACKEND
  GLITCHES_BACKEND

  FLOORS_BACKEND
  ROOM_STATUSES_BACKEND
  ROOM_HOUSEKEEPINGS_BACKEND
  ROOM_CATEGORIES_BACKEND
  ROOM_NOTES_BACKEND
  CATALOGS_BACKEND
  USERS_BACKEND
  GROUPS_BACKEND
  ASSETS_BACKEND
  VIRTUAL_ASSETS_BACKEND
  ROOM_AREAS_BACKEND
  CUSTOM_ACTIONS_BACKEND
`);
