import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET

  ROOM_CLEAN_START
  ROOM_CLEAN_RESTART
  ROOM_CLEAN_PAUSE
  ROOM_CLEAN_UNPAUSE
  ROOM_CLEAN_FINISH
  ROOM_CLEAN_FLUSH

  ROOM_DELAY
  ROOM_DND
  ROOM_REFUSE
  ROOM_INSPECT
  ROOM_NO_CHECK
  ROOM_CONFIRM_DND
  ROOM_CANCEL
  ROOM_RESET
`);
