import { createTypes } from 'reduxsauce';

export default createTypes(`
  OUTBOUND_RESET

  OUTBOUND_ROOM_CLEAN_START
  OUTBOUND_ROOM_CLEAN_RESTART
  OUTBOUND_ROOM_CLEAN_PAUSE
  OUTBOUND_ROOM_CLEAN_UNPAUSE
  OUTBOUND_ROOM_CLEAN_FINISH

  OUTBOUND_ROOM_DELAY
  OUTBOUND_ROOM_DND
  OUTBOUND_ROOM_REFUSE
  OUTBOUND_ROOM_INSPECT
  OUTBOUND_ROOM_NO_CHECK
  OUTBOUND_ROOM_CONFIRM_DND
  OUTBOUND_ROOM_CANCEL
  OUTBOUND_ROOM_RESET

  OUTBOUND_ROOM_MODEL_UPDATE
  OUTBOUND_ROOM_ATTENDANT_INSPECT

  OUTBOUND_ROOM_UPDATE_SUCCESS
  OUTBOUND_ROOM_UPDATE_FAILURE
  
  OUTBOUND_LOG_OTHER
  OUTBOUND_LOG_CLEAN
  OUTBOUND_LOG_COMPLETED
  OUTBOUND_LOG_FAILURE

  OUTBOUND_SUBMIT_FOUND_ITEM
  OUTBOUND_SUBMIT_FOUND_ITEM_SUCCESS
  OUTBOUND_SUBMIT_FOUND_ITEM_FAILURE

  OUTBOUND_TASK_CREATE
  OUTBOUND_TASK_CREATE_SUCCESS
  OUTBOUND_TASK_CREATE_FAILURE

  OUTBOUND_TASKS_CREATE
  OUTBOUND_TASKS_CREATE_SUCCESS
  OUTBOUND_TASKS_CREATE_FAILURE

  OUTBOUND_TASK_UPDATE
  OUTBOUND_TASK_UPDATE_SUCCESS
  OUTBOUND_TASK_UPDATE_FAILURE

  OUTBOUND_TASK_UPDATE_BATCH
  OUTBOUND_TASK_UPDATE_BATCH_SUCCESS
  OUTBOUND_TASK_UPDATE_BATCH_FAILURE

  OUTBOUND_TASK_REASSIGN
  OUTBOUND_TASK_REASSIGN_SUCCESS
  OUTBOUND_TASK_REASSIGN_FAILURE

  OUTBOUND_TASK_CONVERT
  OUTBOUND_TASK_CONVERT_SUCCESS
  OUTBOUND_TASK_CONVERT_FAILURE

  OUTBOUND_GLITCH_UPDATE
  OUTBOUND_GLITCH_UPDATE_SUCCESS
  OUTBOUND_GLITCH_UPDATE_FAILURE

  OUTBOUND_NOTIFICATION_CREATE
  OUTBOUND_NOTIFICATION_CREATE_SUCCESS
  OUTBOUND_NOTIFICATION_CREATE_FAILURE

  OUTBOUND_LF_CREATE_UPLOADING_PHOTO
  OUTBOUND_LF_CREATE_APPLY_PHOTO
  OUTBOUND_LF_CREATE_FAILURE

  OUTBOUND_LF_SUBMIT
  OUTBOUND_LF_SUBMIT_SUCCESS
  OUTBOUND_LF_SUBMIT_FAILURE
`);
