import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET_ROOMS

  ROOM_ACTIVATE
  ROOM_DEACTIVATE

  ROOMS_FETCH
  ROOMS_SUCCESS
  ROOMS_FAILURE

  ROOM_UPDATE_OPTIMISTIC
  ROOM_UPDATE_SUCCESS

  FLOORS_FETCH
  FLOORS_SUCCESS
  FLOORS_FAILURE

  ROOM_STATUSES_FETCH
  ROOM_STATUSES_SUCCESS
  ROOM_STATUSES_FAILURE

  ROOM_HOUSEKEEPINGS_FETCH
  ROOM_HOUSEKEEPINGS_SUCCESS
  ROOM_HOUSEKEEPINGS_FAILURE

  PLANNINGS_FETCH
  PLANNINGS_SUCCESS
  PLANNINGS_FAILURE

  PLANNINGS_NIGHT_FETCH
  PLANNINGS_NIGHT_SUCCESS
  PLANNINGS_NIGHT_FAILURE

  PLANNINGS_RUNNER_FETCH
  PLANNINGS_RUNNER_SUCCESS
  PLANNINGS_RUNNER_FAILURE

  CALENDAR_FETCH
  CALENDAR_SUCCESS
  CALENDAR_FAILURE

  ROOM_NOTES_FETCH
  ROOM_NOTES_SUCCESS
  ROOM_NOTES_FAILURE

  CATALOGS_FETCH
  CATALOGS_SUCCESS
  CATALOGS_FAILURE

  TASKS_FETCH
  TASKS_SUCCESS
  TASKS_FAILURE

  TASK_UPDATE_OPTIMISTIC
  TASK_UPDATE_SUCCESS

  HISTORY_FETCH
  HISTORY_SUCCESS
  HISTORY_FAILURE
`);
