'use strict';

exports.__esModule = true;

var _reduxsauce = require('reduxsauce');

exports['default'] = (0, _reduxsauce.createTypes)('\n  RESET_ROOMS\n\n  ROOM_ACTIVATE\n  ROOM_DEACTIVATE\n\n  ROOMS_FETCH\n  ROOMS_SUCCESS\n  ROOMS_FAILURE\n\n  FLOORS_FETCH\n  FLOORS_SUCCESS\n  FLOORS_FAILURE\n\n  ROOM_STATUSES_FETCH\n  ROOM_STATUSES_SUCCESS\n  ROOM_STATUSES_FAILURE\n\n  ROOM_HOUSEKEEPINGS_FETCH\n  ROOM_HOUSEKEEPINGS_SUCCESS\n  ROOM_HOUSEKEEPINGS_FAILURE\n\n  PLANNINGS_FETCH\n  PLANNINGS_SUCCESS\n  PLANNINGS_FAILURE\n\n  PLANNINGS_NIGHT_FETCH\n  PLANNINGS_NIGHT_SUCCESS\n  PLANNINGS_NIGHT_FAILURE\n\n  PLANNINGS_RUNNER_FETCH\n  PLANNINGS_RUNNER_SUCCESS\n  PLANNINGS_RUNNER_FAILURE\n\n  CALENDAR_FETCH\n  CALENDAR_SUCCESS\n  CALENDAR_FAILURE\n\n  ROOM_NOTES_FETCH\n  ROOM_NOTES_SUCCESS\n  ROOM_NOTES_FAILURE\n\n  CATALOGS_FETCH\n  CATALOGS_SUCCESS\n  CATALOGS_FAILURE\n\n  TASKS_FETCH\n  TASKS_SUCCESS\n  TASKS_FAILURE\n\n  TASK_UPDATE_SUCCESS\n');