'use strict';

exports.__esModule = true;

var _reduxsauce = require('reduxsauce');

exports['default'] = (0, _reduxsauce.createTypes)('\n  UPDATES_RESET\n\n  INVENTORY_ADJUST\n  INVENTORY_RESET\n  INVENTORY_FLUSH\n  INVENTORY_RESTOCK\n\n  ROOM_CLEAN_START\n  ROOM_CLEAN_PAUSE\n  ROOM_CLEAN_UNPAUSE\n  ROOM_CLEAN_FINISH\n  ROOM_CLEAN_FLUSH\n\n  ROOM_DELAY\n  ROOM_DND\n  ROOM_REFUSE\n  ROOM_NO_CHECK\n  ROOM_CONFIRM_DND\n  ROOM_CANCEL\n\n  ROOM_NOTE_ADD\n  ROOM_NOTE_REMOVE\n\n  PHOTO_UPLOAD\n  PHOTO_STORE\n  PHOTO_REMOVE\n\n  LOST_ITEM_ADD\n\n  TASK_CREATE\n  TASK_UPDATE\n');