import { createTypes } from 'reduxsauce';

export default createTypes(`
  UPDATES_RESET

  INVENTORY_ADJUST
  INVENTORY_REJECT
  INVENTORY_RESET
  INVENTORY_FLUSH
  INVENTORY_RESTOCK

  ROOM_CLEAN_START
  ROOM_CLEAN_RESTART
  ROOM_CLEAN_PAUSE
  ROOM_CLEAN_UNPAUSE
  ROOM_CLEAN_FINISH
  ROOM_CLEAN_FLUSH

  ROOM_DELAY
  ROOM_DND
  ROOM_REFUSE
  ROOM_INSPECT
  ROOM_NO_CHECK
  ROOM_CONFIRM_DND
  ROOM_CANCEL
  ROOM_RESET

  ROOM_HOUSEKEEPING
  ROOM_COMMENT
  ROOM_GUEST_LOCATOR
  ROOM_UNBLOCK

  ROOM_RESTOCK
  ROOM_TURNDOWN

  PLANNING_USER

  ROOM_NOTE_ADD
  ROOM_NOTE_REMOVE

  PHOTO_UPLOAD
  PHOTO_UPLOAD_SUCCESS
  PHOTO_UPLOAD_FAILURE

  PHOTO_STORE
  PHOTO_REMOVE

  LOST_ITEM_ADD
  LOST_ITEM_ADD_SUCCESS
  LOST_ITEM_ADD_FAILURE

  TASK_CREATE
  TASK_UPDATE
  TASK_CONVERT
  TASK_CREATE_BATCH
  TASK_UPDATE_BATCH
  TASK_REASSIGN

  TASK_CREATE_SUBMIT
  TASK_CREATE_UPLOADING_PHOTO
  TASK_CREATE_APPLY_PHOTO
  TASK_CREATE_SUCCESS
  TASK_CREATE_FAILURE

  TASK_SENDING
  TASK_SENDING_SUCCESS
  TASK_SENDING_FAILURE
  TASK_SENDING_RESET

  NOTIFICATION_CREATE

  SAVE_OUTGOING_HASH
`);
