import { createTypes } from 'reduxsauce'

export default createTypes(`
  ASSETS_RESET

  ASSETS_FETCH
  ASSETS_SUCCESS
  ASSETS_FAILURE

  VIRTUAL_ASSETS_FETCH
  VIRTUAL_ASSETS_SUCCESS
  VIRTUAL_ASSETS_FAILURE

  ASSET_ROOMS_FETCH
  ASSET_ROOMS_SUCCESS
  ASSET_ROOMS_FAILURE

  CUSTOM_ACTIONS_FETCH
  CUSTOM_ACTIONS_SUCCESS
  CUSTOM_ACTIONS_FAILURE

  ROOM_AREAS_FETCH
  ROOM_AREAS_SUCCESS
  ROOM_AREAS_FAILURE

  INVENTORY_WITHDRAWAL_FETCH
  INVENTORY_WITHDRAWAL_SUCCESS
  INVENTORY_WITHDRAWAL_FAILURE
`)
